name: Trigger auto deployment for test-container-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/test-container-app-AutoDeployTrigger-e82acc74-fd35-4601-a06b-d67e82fec466.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.TESTCONTAINERAPP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.TESTCONTAINERAPP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.TESTCONTAINERAPP_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: 
          registryUsername: ${{ secrets.TESTCONTAINERAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.TESTCONTAINERAPP_REGISTRY_PASSWORD }}
          containerAppName: test-container-app
          resourceGroup: sekarrg
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


